package _89GrayCode;

import java.util.ArrayList;
import java.util.List;

public class Solution {
    public List<Integer> grayCode(int n) {
        // gray code sequence for n digit could be recursively generated by gray code sequence for n-1 digit
        List<Integer> arr = new ArrayList<>();
        arr.add(0);
        if (n < 1) {
            return arr;
        }
        arr.add(1);
        int fac = 1;
        for (int i = 1; i < n; i++) {
            fac = fac << 1;
            for (int j = arr.size()-1; j >= 0; j--) {
                arr.add(arr.get(j) + fac);
            }
        }
        return arr;
    }
}
